### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#118]
Hi,

unfortunately I have to inform you that Urban Biker constantly crashes on my new mobile phone:
Xiaomi Mi 10
Android 11 RKQ1.200826.002
MIUI Global 12.2.4
Urban Biker v5.2000 and v5.2001
I am using UB in split screen.

I already excluded UB app from all energy saving/management functions, but still constantly crashes occur and I have to start UB again every time (track recording then is continued).

Sorry for not being able to provide much more details, but maybe there are any crash logs in the file system I could send to you?

Don't even know whether it is an UB issue or relating to Android or MIUI version.

Thanks for any hints, 
Andreas

**Comment by Sublimis** [comment]
Hi Andreas, sorry for the late reply. We waited to see if we can get a crash report from the Google Play, to be able to tell what is happening and why. We did found a crash report, but unfortunately it's too generic and not much of a help. Here it is:

`android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2047)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:7876)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)`

This exact crash report (with exactly the same line numbers) appears on Xiaomi Mi 10, Mi 10 lite 5G, and Poco F2 Pro devices, all on Android 11. We do not know how to proceed from here, as the crash doesn't mention our code. App was tested on Android 11, and didn't crash once. Also, other Android 11 devices do not report the crash. Thus we suspect the problem is with MIUI, and some future update will hopefully fix it.

Sorry we couldn't be of more help. Thanks for the feedback!

**Comment by Scooty66** [comment]
Hi Sublimis,

thanks a lot for looking into the issue.
Well, good to hear that other, similar devices run into the same issues, at least I am not alone. :-)
OK, next update for MIUI to version 12.5 is scheduled for Q2/2021, until then I will be using my old device Mi Mix 2S with MIUI 12.0.3.0 and Android 10.
Nevertheless, based on your response I filed a feedback with the Xiaomi MIUI guys (but hopes are very low, that anyone will look at it at all...).

Thanks for your support,
Andreas

PS:
I leave this issue open, just ran into another crash when trying to edit properties of my power/cadence sensor from Assioma.
Will have to reinstall/reconnect it and let you know whether this might be the cause for the crashes. Strange thing is, the sensor  worked fine ad showed correct values at times when UB was running. Anyway, I am not sure that the other devices you mentioned above do use the same sensor.....
I'll keep you updated.

**Comment by Scooty66** [comment]
Short update:
Repairing of the sensor(s) did not help, UB still crashes.
So now waiting for MIUI (or any other system) update(s).

**Comment by Scooty66** [comment]
Just to let you know that in the meantime everythings works stable and fine with my Xiaomi Mi 10.
There was an intermediate update on MIUI to 12.2.7 and of course some UB updates to version 6.02.
So no idea what helped in the end, but thanks for you continuous support and development.

Andreas

**Comment by Sublimis** [comment]
This is great news, thanks for the feedback! We did fix some crashes regarding translations, i.e. the app was crashing for some users not using English language, caused by errors in translations. If that's not it, than it must be MIUI update that helped 🙂
