### ISSUE TITLE
Multple Metrics per line.. Has this been implemented?  The screenshots show 2 per line but I can't find how to do it?

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#136]
Has this been implemented?  The screenshots show 2 per line but I can't find how to do it?

<img width="673" alt="Screen Shot 2021-06-18 at 10 13 48 PM" src="https://user-images.githubusercontent.com/5296383/122628162-98a1d280-d082-11eb-8644-ea8ec5ed3d64.png">

_Originally posted by @surge919 in https://github.com/Sublimis/UrbanBiker/issues/8#issuecomment-864341718_

**Comment by Sublimis** [comment]
Hi! This screen is known as the "Overview" screen (previously known as the "Summary" screen) and it's been a part of the app since almost forever. 🙂 You can access it from the main menu, by sliding from the left side of the display and clicking the "Overview" menu item.

Multiple metrics per line customization of the main app screen is not available yet, but we started preparations and plan on implementing this probably during the next several months.

Hope this helps. Thanks for the feedback!

**Comment by surge919** [comment]
i've only been using this app for a week and I missed that Overview screen.  I'll use that for now and look forward to be able to add extra metrics.

thanks

**Comment by radiotbo** [comment]
Please, please!!! It is the only festure I really missed. I just need 1 or 2 more metrics

**Comment by Sublimis** [comment]
If we can suggest an alternative approach on how to work around this until the "additional meters on main screen" feature is implemented.

1. Choose one meter you want to use for additional metrics (modes). We suggest using the bottom meter or the top meter for this.
2. Long-tap on the selected meter until a menu pops-up. Select "_Meter mode..._" from the menu, then scroll all the way down and select "_Choose modes..._".
3. Disable (uncheck) **all** modes except the 1 or 2 extra modes you're interested in having on the main screen. Click _OK_ to confirm.
4. Long-tap the meter again, and disable (uncheck) the "_Lock_" from the menu to make the meter clickable.

Now you can simply tap the meter to toggle between the metrics of interest. When there are only 2 or 3 available metrics on a meter, this can be quite convenient.

Hope this helps!
