### ISSUE TITLE
Clarification of an item from the changelog - indicator from external sensor

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#143]
I also posted this on the reddit forum

@Sublimis 

What do you mean by the following entry?

v6.03 2021-06-28
"⚡ Indicator when data comes from an external sensor (rather than the GPS or an internal sensor) "

Should I see some indication that the speed being displayed is from my speed sensor vs the phone's GPS?

I have 3 sensors
Heartrate (polar)
cadence (garmin)
speed (garmin)

they all show that they are detected and used in the profile but the indicator is sometimes still yellow.
If I stop recording and start, occasionally it turns green until I stop of pause it.  if the icon turns yellow, the pause and restart sometimes makes it turn green

btw:  I've manually set the wheel circumference

**Comment by Sublimis** [comment]
Hi @surge919, "external sensor indicator" is a small pulse-like icon in the top-right corner of a particular meter field, like shown in the picture below. It won't be shown on the big speedometer field, though, because that's not implemented as of v6.07.

Yellow "sensors" indicator on top of the screen in your case just means that sensor data was not yet received (if the sensor just connected), or wasn't received for the last 90 seconds. This can happen during normal operation e.g. on long descents when pedals are not turned for several minutes, so the cadence sensor doesn't send any data. Otherwise, it can also happen when sensor magnet falls off.

Hope this helps. Thanks for the feedback!

![image](https://user-images.githubusercontent.com/3844660/133677192-d16dec15-4e6f-4e77-aeb6-77cf7302195e.png)

**Comment by surge919** [comment]
I set one of the regular boxes to show speed but it doesn't show the pulse.
the sensors section shows that my speed sensor is detected and the properties are set to the following:
Use for speed: enabled
Use for cadence: disabled
Use for distance and duration: enabled

Wheel circumference is manually set

![Screenshot_20210922-183455](https://user-images.githubusercontent.com/5296383/134435814-34e8a1fd-ed93-459e-8630-7f99264b1e2c.png)
![Screenshot_20210922-183505](https://user-images.githubusercontent.com/5296383/134435845-feb2bb15-9fcd-462c-8ae2-adb3f0762e33.png)

**Comment by Sublimis** [comment]
The pulse icon in a meter will show only when the value displayed came from a sensor (and not the GPS). In your example this is not the case. The value of 10.2 mph shown came from the GPS, and appears to be an erroneous value caused by EM interference.

This is easily explained by noting that you're standing still; cadence is zero. Since you're standing still, speed sensor stopped sending data (but is still connected, thus the upper icon is green). When there's no data from the sensor for more than about 10 seconds, the app will allow GPS data to go through, and this is what happened here.

To mitigate such behavior, please consider enabling one of the following options in **Settings > Tracking/GPS** (or both):

- **GPS automatic sleep**, and
- **Reduce location noise**.

Please see the screenshot below.

![physical_activity_recognition](https://user-images.githubusercontent.com/3844660/134778025-d68c8684-37d5-4193-a5c5-ffe49a4f8444.png)

**Comment by surge919** [comment]
I think there was a conflict with the Garmin software.  I unpaired the sensors from the app and it's been working fine.

btw.. my screenshot was taken while coasting so the cadence was zero.

thanks
