### ISSUE TITLE
Keep sensors active when app is running

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#162]
Would it be possible to have an option in settings to keep sensors active while the app is running?

I have trouble with some sensors not getting picked up when I start recording.  This is fixed by pressing pause and then resuming.

I know we can long press record to get the sensors working before starting the recording but once I pause again, it routinely loses the HR sensor.. a quick pause and resume usually fixes it.

**Comment by Sublimis** [comment]
Hi! The app connects sensors when recording starts (whether paused or not), and disconnects when recording stops. When recording is active, pausing does not change connected state of the sensors; they stay connected (if possible*).

By "pausing" we mean when the recording button changes appearance to two vertical lines like this: ⏸️. This can happen either by long-pressing the record button, or by using auto-pausing. Everything else is either "recording" or "stopped". You mention "pause" three times, but probably mean "stop"? If this is so, we suggest using the real pausing (long-pressing the record button) instead of stopping when you take a short break. Please correct us if we misunderstood something.

* Please keep in mind that sensors can go to sleep and disconnect on their own when left unused, this is a battery saving feature. It can take some time for a sensor to wake up and connect again, sometimes even 30 seconds or so.

Thanks for the feedback!

**Comment by surge919** [comment]
i had forgotten about press/hold being Pause.  The auto-pause sometimes works when I initially stop at a light, but un-pauses after a few seconds with no movement so I always press the button at long lights.

Could you flip the behavior or make it a selectable option?

1) single press for pause    press/hold for stop
2) single press for stop     press/hold for pause

**Comment by Sublimis** [comment]
Auto-pause unpausing after a few seconds is most probably induced by GPS noise in this case. Please enable the option **Settings > Tracking/GPS > Activity recognition > Reduce location noise**, this could help. Do  you use speed sensor?

Yes, adjustable behavior of the rec button shouldn't be a problem, we just have to find some clever place where to put the option. 🙂 Thanks for the feedback!

**Comment by surge919** [comment]
yes I do have a speed sensor.
I have Garmin speed and cadence sensors.
for the Speed sensor I have enabled "Use for distance and duration"

I'll enable "Reduce location noise" on my next ride

about the button, how about the dual button like you have for the Stop/Finish (with the finish flag at the top right)
the main button
![record-finish](https://user-images.githubusercontent.com/5296383/155736310-2a73b237-3102-44c8-b6b8-f021122ab0d6.png)

Main button could pause and top right button would stop

**Comment by Sublimis** [comment]
> Please enable the option **Settings > Tracking/GPS > Activity recognition > Reduce location noise**, this should help.

Sorry, forgot to say that activity recognition won't work due to a bug present in all v7.x versions released so far. Fix for this is coming with the next release, v7.12. Alternatively, you can try using v6.11 (dated 2021-10-21) until then. Thanks!

**Comment by surge919** [comment]
> Sorry, forgot to say that activity recognition won't work due to a bug present in all v7.x versions released so far. Fix for this is coming with the next release, v7.12. Alternatively, you can try using v6.11 (dated 2021-10-21) until then

no problem.. I like the added items so I'll manually pause for now.

**Comment by Sublimis** [comment]
> Main button could pause and top right button would stop

Interesting suggestion, we'll give it a thought (any maybe provide a third option for this). Thanks again!

**Comment by surge919** [comment]
I noticed this was added a few versions ago.
This is very helpful.
The AutoPause doesn't work well (at least for me) but this button makes it easy to simply tap the screen.  I like how it alerts when you start moving and forget to unpause.

thanks again
