### ISSUE TITLE
Option for not showing 10-minute charts?

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#163]
Hi there,

version 7.04 introduced small 10-minute charts in some meters.
I am using Urban Biker in split screen, with the 10-minute charts the numbers of the meters get very small (see screenshot) and I cannot read them anymore.
Is there an option to switch these 10-minute charts off?

Thanks for that brilliant app and your support,
Andreas
![Screenshot_2022-01-30-12-13-53-913_com sublimis urbanbiker](https://user-images.githubusercontent.com/5012764/152196917-b23c353f-d063-42ae-816e-03214cd96437.png)

**Comment by Sublimis** [comment]
Hi, things are not done yet in the beta version you're using, so unfortunately there's no such option (except in the Overview screen, but it does not persist yet). But the option will certainly be available via a pop-up menu after a long-click on a meter. We're improving meter layout customization intensively these days, so be sure to use the latest beta release to get better results than shown in the screenshot above!

Unrelated question, how did the maximum speed get to be 282.7 km/h? Which phone are you using, and do you have the "Recalculate speed" option enabled (in Settings > Tracking/GPS > Advanced)? If this is due to our app, it may have already been fixed, as we have also made a few improvements regarding GPS (for the next beta release).

Thanks for the feedback!

**Comment by Scooty66** [comment]
Hi,
thanks for the swift reply and explanation.
Good to hear that you are planning to make these charts optional.

In regards to speed: that's how fast I go with my velomobile. :-)
Just joking,, on a more serious note, it does not seem to be due to your app. Currently my Xiaomi Mi 10 mobile has some issues with GPS reception in some areas/circumstances. Still trying to figure out what's could be the problem. Not only Urban Biker is affected but also other apps using GPS....
And yes, for Urban Biker the "Recalculate speed" option is enabled.

**Comment by Scooty66** [comment]
Thanks a lot, option for disabling charts in meters now available and working perfectly (version 7.10).
