### ISSUE TITLE
GPS problems on Xiaomi devices with Android 11

### ISSUE THREAD

**Issue by iRomanyshyn** [Sublimis/UrbanBiker#165]
Hi! I'm using POCO X3 NFC (MIUI 12.5.4 based on Android 11) which is the same as widely popular Xiaomi devices. UB version is 7.04 beta from Play Store. And there is the problem with GPS which prevents me from using the application because after some time I leave my phone untouched in a pocket UB can't get location data just like I'm inside some big building. I'm pretty sure it's because there is no Always Allow option for geolocaton. So that Very Smart Chinese Technology just disabling the GPS when display is locked. I'm using another application with the same power saving options and it works fine. The only one difference in the settings is Always Allow for geolocaton. I can't remember when it happened for a first time but it was several months ago. Also, what is happening with file system access? It's horrible. Please, check what guys from Syncthing Android doing with that problem because they can just use any folder for reading and writing except for system special folders.

**Comment by Sublimis** [comment]
Hi!

Both of the points you mention (GPS doesn't work in background, and filesystem not accessible globally) are caused by recent changes in Android with the aim of improving privacy and battery life, and for now this can't be solved by our app alone.

To try solving the GPS issue, we recommend examining procedures laid out here: [https://dontkillmyapp.com/xiaomi](https://dontkillmyapp.com/xiaomi). "Always Allow" option wouldn't help. As explained in the [official documentation](https://developer.android.com/training/location/permissions#request-background-location), this option allows the app to access location in the background. This doesn't mean "when display is locked", but rather "when the app is not visible nor interacted with". Urban Biker always uses GPS transparently in the _foreground_, visible as an icon in the notification area. Even if we are to request background locations, note [this part](https://developer.android.com/about/versions/oreo/background-location-limits):

> In an effort to reduce power consumption, Android 8.0 (API level 26) limits how frequently an app can retrieve the user's current location while the app is [running in the background](https://developer.android.com/guide/background). Under these conditions, apps can receive location updates only a few times each hour.

So apps accessing locations in the background receive location updates **only a few times each hour**, and this is not good enough for the tracking app, nor was it intended for tracking apps.

As for the file system access, the story is similar. In principle we *could* request ["All files access"](https://developer.android.com/training/data-storage/manage-all-files) permission, however Google would then remove the app from the Play Store. _All files access_ permission is regarded as _dangerous_ and is intended only for those app which require such permission for their core functionality, such as file managers, backup or antivirus apps. This is what Syncthing does, [as can be seen here](https://github.com/syncthing/syncthing-android/blob/main/app/src/main/AndroidManifest.xml).

Please note, there's nothing stopping you to move all your track files from the old folder `/Documents/UrbanBiker/tracks` to the new folder `/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/tracks`, and simply ignore the "Custom tracks folder" feature in the app (if this is what bothers you regarding file system?). We decided not to do this automatically to prevent possible complete data loss if a user not yet familiar with the change decides to reinstall the app wiping all its data.

Hopefully this helps a bit. Thanks for the feedback!

**Comment by iRomanyshyn** [comment]
Yeah, I know Xiaomi is a pain on the ass. But [RunnerUp](https://github.com/jonasoreland/runnerup) works fine with almost the same settings. I allowed anything for both applications except disabling MIUI optimizations. I'm using RunnerUp every day to record my commute walks and used it to track bicycle ride. I don't know, maybe they added some hacks but it works.

**Comment by iRomanyshyn** [comment]
I set the policy to "Fully awake" but it doesn't help. I don't know what is changed between UB versions but it made me to switch to another app. I tried just walk home from work and it can't find GPS after several minutes if screen is locked.

**Comment by Sublimis** [comment]
In v7.10 of the app released a few days ago we did one change that could possibly fix this. Is it possible for you to try it? Just make sure that _GPS provider_ option is set to **Google Play services** in the _Settings > Tracking/GPS > Advanced_ beforehand. Thanks!

**Comment by Sublimis** [comment]
Given that no one mentions this problem anymore, it's probably safe to assume that the problem has been solved.

It seems that the "trick" to make it work was to make sure the "Google Location Services API" (Fused location provider) is used to obtain device locations, and not the "android.location" API (as it was previously sometimes possible even when the option was set to Google Play services).
