### ISSUE TITLE
UI/UX problems

### ISSUE THREAD

**Issue by iRomanyshyn** [Sublimis/UrbanBiker#166]
![Screenshot_2022-02-13-19-48-14-254_com sublimis urbanbiker](https://user-images.githubusercontent.com/11888301/153768452-e732b180-02b6-4882-b92f-497d9a51e1a1.jpg)

Hello! Something bad happens when Urban Biker works on some MIUI 12.5 (Xiaomi, Mi, POCO) device with Night Mode (or Dark Mode) enabled. I know it's not native but it works fine on 95% of applications and on 99% of system UI. Also, that squares near counter icons — I don't have any idea what is that.

Also, there is very bad UX for the first start.

It's there any UI/UX rework planned? Because I'm sure Urban Biker needs to be simplified and synchronized with some guidelines to become better for inexperienced user.

**Comment by Sublimis** [comment]
Hi! Is it true that the display is fixed by launching the app again? If yes, then we think this is now fixed for the next version release.

Squares are small charts, which becomes apparent when you start tracking :) UX rework, yes, probably with some small tutorial when the app is first started, but alas, there's always some more important work to be done. Apart from this, small incremental UX improvements are done continuously, like info (quick help) dialogs, etc. Also, some big UI improvements are coming soon (version after the next one), which will enable much better display customization, and in the future the possibility to quickly change display layout by using "themes".

Thanks for the feedback!

**Comment by iRomanyshyn** [comment]
![Screenshot_2022-02-15-20-49-10-403_com sublimis urbanbiker](https://user-images.githubusercontent.com/11888301/154129061-39757793-f236-47c2-99ab-c96a4b668283.jpg)
![Screenshot_2022-02-15-20-50-35-312_com sublimis urbanbiker](https://user-images.githubusercontent.com/11888301/154129064-506a41ce-84cd-4ace-bffc-a540f1cedf0d.jpg)
Here are two screenshots. The first one is with Dark Mode enabled, and the second is how it looks without Dark Mode.

**Comment by Sublimis** [comment]
Hi, is this fixed now in recent app versions?
