### ISSUE TITLE
App crashes trying to send a recorded track

### ISSUE THREAD

**Issue by fbsoftware-stuttgart** [Sublimis/UrbanBiker#181]
Hi,

since v7.50 (2022-11-15) the app crashes, when i try to send (share) a recorded track.

I use the app with Android on my Samsung SM-A530F/DS Galaxy A8 Duos (2018).

Maybe you could look into this and provide a fixed version.

Thanks.

**Comment by Sublimis** [comment]
Hi, terribly sorry, somehow we missed this issue, which also happens when FenceGuard is invoked from the main menu as well. This has been fixed and the fixed version is now available on the Play Store. The version number is the same, v7.50, but is dated 2022-11-17. We hope users won't be annoyed by updates only a day apart... 🙂 Thanks for this!
