### ISSUE TITLE
Suggestion: Ability to remove datetime string from activity title

### ISSUE THREAD

**Issue by anton-vakulenko** [Sublimis/UrbanBiker#188]
It would be nice feature if user could remove datetime string from activity title. I mean the ability to change default title format 'My cool MTB No. 2 - Sun, Apr 20, 2023, 6:01 am' to simple 'My MTB No. 2'. This datetime information already exists in history and in any webapp (strava etc), so it just bloats the title (IMHO).

And thank you very much for great app and the ability to customize screen layout!!!

**Comment by Sublimis** [comment]
Hi, there is no option because we decided it would be redundant. Can you please explain the use case where you need the date and time in the track title? Would that justify giving an option in the settings? Since the date and time of the track is provided in other places, usually near the title (eg in the subtitle), both in the list and in the charts, the option seems unnecessary.
