### ISSUE TITLE
Strava upload: Time in motion same as total time

### ISSUE THREAD

**Issue by fertigfutter** [Sublimis/UrbanBiker#195]
<=v 7.105
Recorded trip times are differentiated into total and time in motion. But when exported into Strava total time is inserted for both fields. Time in movement is ignored.

**Comment by Sublimis** [comment]
Hi, we cannot replicate this issue.

Does the info on this page help? https://support.strava.com/hc/en-us/articles/115001188684-Moving-Time-Speed-and-Pace-Calculations

(especially the part that lists exceptions to the moving time rule, eg. "If a run activity is tagged as a race, we will use elapsed time")

Please let us know. Thanks for the feedback!

**Comment by fertigfutter** [comment]
Well, the problem persists. The Strava help page didn't help.
I use my bike at home without GPS, it's tagged as training, I pause manually. There are clearly two different times: time overall and time in movement. If the training is exported to strava, there is only one time for both data fields and it is the total time including breaks. Unfortunately, this renders all other values ​​unusable: average, FTP, etc. It looks to me as if Strava calculates stupidly from start time to end time and completely ignores automatic or manual breaks. Perhaps it is necessary to fool Strava regarding end time by subtracting pause times before data export.

**Comment by Sublimis** [comment]
This should be fixed in the new v7.106, but please let us know after you confirm.

You are right about the way Strava calculates moving times, but this is probably not just their fault. Since this is the indoor training, they can't calculate speeds using GPS locations to determine when the user was pausing (based on some minimum speed value), because, obviously, there are no GPS locations. And there is no other way for our app to explicitly tell Strava what the moving time was. Whether this is a bug or a feature on their end is hard to say, but the workaround was pretty obvious. UrbanBiker will now create a new "segment" in a track when you pause/resume, so Strava knows not to include time between segments even without GPS coordinates.

**Comment by fertigfutter** [comment]
Unfortunately the problem still occurs (here).

**Comment by fertigfutter** [comment]
OK, thank you!

Daniel

Urban Biker ***@***.***> schrieb am Di., 30. Jan. 2024, 02:09:
