### ISSUE TITLE
Speedometer not very responsive?

### ISSUE THREAD

**Issue by motobird** [Sublimis/UrbanBiker#21]
I noticed that the speedometer took anywhere from 6 to 12 seconds for it to drop back to 0 after I stopped. This was with the default 1-second GPS update rate.

**Comment by motobird** [comment]
I just tried it with GPS tracking set to 'fastest' under open sky and the same thing happened (took up to 12+ seconds for the speed to drop back to 0).

**Comment by motobird** [comment]
Does anybody have this same problem?

**Comment by Sublimis** [comment]
Hi, we are currently testing a solution, which required some unavoidable changes to the tracking code. The solution looks well for now, and the next version update most probably won't manifest the behavior you described. Thanks for the feedback!

**Comment by motobird** [comment]
I just updated to v5.07. When stopped, the speed still took several seconds to drop back to 0. It's better than before but still very noticeable. I would say from at least 3 to 7 seconds for it to drop to 0.

What I don't understand is: the moving time stopped immediately as soon as I stopped. After the moving time stopped, it took several more seconds for the speed to drop back to 0. Why can't the 0 speed tied to the moving time?  E.g, as soon as the moving time stopped, the speed should stop too, no?

**Comment by Sublimis** [comment]
Sorry for the late reply. You can make the speed more responsive by unchecking the option **Recalculate speeds** in **Settings > Tracking/GPS > Advanced**.

When this option is _checked_, speeds are being calculated as _distance/duration_, using GPS location points to calculate distances and duration. This is rather inaccurate method, so it must go through a filter. Filter introduces additional (unavoidable) delay of about 2.5 seconds on average, and this is what you would perceive as unresponsiveness.

When the option is _unchecked_, speeds are taken directly from the GPS hardware which calculates them using the Doppler effect on GPS electromagnetic signals. In this case the app won't do filtering. However, in urban areas this method can be more inaccurate than the first method, given the signals are weak (must travel 20'000 km from the satellite to the Earth) and interference is usually strong.

This is why speed recalculation is considered more robust, so is currently the default, and the 'Recalculate speeds' option will be enabled when the app is installed.

We suggest you to try disabling this option and see how it goes. If you notice erratic speed values, then it's best to revert to the default.

**Comment by motobird** [comment]
Thanks for the reply. I don't think that was it. The option on mine was "unchecked". Just tested it and it took 5-7 seconds after I stop for the speedometer to slowly drop back to 0. Anyway, did you see this too? It's very trivial. Thanks again. Again, the display duration time stopped immediately as soon as I stop, so that's correct.

**Comment by Sublimis** [comment]
Hi, thank you for your feedback. This is quite strange behavior, almost exactly like in older app version (before this was fixed). Just to be clear, you are not using a wireless speed sensor, only GPS? Can you please double-check that you are using the latest app version by going to the About screen (v5.14 at this moment). Also check that your '**GPS update interval**' is set to Default (you can check this from the Control Panel dialog).

If all of the above conditions are met, the only situation where this behavior will happen is if no GPS locations are received for some time after you stop ('recalculate speed' is enabled) -or- the locations received do not contain speed information ('recalculate speed' is disabled).

Normally, when you are out in the open your phone should receive one GPS location every ~1 second, whether you are riding or stopped. When riding, GPS locations contain speed information different from zero (of course). But when you stop, GPS locations should still contain speed information (but equal to zero).

It may be that your GPS hardware has problems detecting zero-speed condition. This is not a trivial task, and in fact it's easier for GPS hardware to detect speed when moving faster. Not all GPS receivers are the same, and it wouldn't surprise us if this is the case, especially if your phone packs a lower-end chipset or some more uncommon one. Can we ask which phone model are you using for tracking?

As for the moving time (duration), it updates only upon receiving GPS location. Since no GPS locations are received after you stop (as we argued above), it's no surprise the duration value won't update.

Hope this helps clear things up a bit. Thank you once again for your feedback!
