### ISSUE TITLE
Sensor detection does not work after upgrading to new phone

### ISSUE THREAD

**Issue by Dieggu** [Sublimis/UrbanBiker#33]
Hi,
I upgraded from a Galaxy Note 4 (Android 6) to an LG G7 Thinq (Android 8).

When scanning sensors, none of my sensors are detected any more. The phone only detects unsupported sensors.
On my Note 4 there are (still detected):
Device: 11836, heart frequency (Garmin Vivosmart 3)
Device: 12633, Cadence (Garmin ANT+)
Device: 64215, Speed, Distance, Duration (Garmin ANT+)

The LG G7 reports only unsupported sensors and detection is also not reliable:
e.g.: "C0:97:27:62:DC:3B"

I already did a reinstall of the app and rebooted my device. No Change.

Any help would be appreciated.

Dieggu

**Comment by Sublimis** [comment]
Hi, your new phone (LG G7) does not support ANT+ protocol. All of your sensors are ANT+ sensors, and that's why they can't be detected on the new phone.

Unfortunately, nothing can be done about this. It seems like newer Android devices are going away from ANT+ and only support BLE protocol, with a few exceptions like some Samsung and Huawei phones and maybe a few others. You can try installing ANT+ service on your phone as explained in our FAQ (http://urban-bike-computer.com/faq/#ant) and then try again, but the chances of it working are slim.

Unsupported sensors with a weak signal that the app picks up are usually appliances from your surroundings, like television sets from your neighbors etc., and can safely be ignored.

**Comment by Dieggu** [comment]
Thanks. So it is as it is.
I installed the ANT+ service, but this still did not work.
I do not like the recommended Topeak device. Do you think it is worth trying this:
https://www.amazon.de/gp/product/B07JN5F2HS/ref=ox_sc_act_title_2?smid=A3FNFU5JZFDCZT&psc=1 ? This is a "CooSpo Sensor for Ant+ and Bluetooth". If you think it's worth it, I'll try and report here.
Do you recommend any heartfrequence sensor?
And it my be worth noting in the FAQ, that newer Android versions have less support for ANT+.

Thanks again and regards,
Dieggu

**Comment by taob** [comment]
Dieguu,

I have a Coospo speed and cadence sensor, and it works fine with UB. The one I have is this model: https://www.amazon.ca/dp/B06XG8VY4X/. I am using this heart rate strap: https://www.amazon.ca/dp/B01LZZ4IJ3/

**Comment by Sublimis** [comment]
Dieggu, we haven't tried any sensor from CooSpo, so can't tell. Similar device we tried is 'Magene Gemini 210', and it worked perfectly so far. It's also magnet-less sensor that can be used for speed or cadence (but not both at the same time-two sensors are needed for this), and relatively cheap.

For heart rate, you can also take a look at Panobike Topeak series, Wahoo Tickr, or Polar for example. Igpsport should probably also work okay, as well as other less known Bluetooth chest straps. We usually do not recommend bracelets as HR sensors, as they usually either do not support sensor mode (to be used as a continuous HR sensor) or are not as accurate as chest straps.

**Comment by Dieggu** [comment]
Hi taob, Sublimis,
Thank you for your valuable inputs! I did some more research and decided for wahoo RPMcadence as cadence sensor. This connected flawlessly to urban biker. I did not decide regarding heart rate. I will either go for the Wahoo Tickr or the Coospo, as I now know, they are compatible.
Thanks again
Dieggu
