### ISSUE TITLE
Mi band 2 hr does not work anymore

### ISSUE THREAD

**Issue by Niflheim123** [Sublimis/UrbanBiker#38]
I haved used successfuly mi band 2 in the past with urban biker, but after recent updates the band appears in the Unsupported category. I would start a workout from the mi band app interface and when I scan for sensors this issue occurs.

**Comment by Sublimis** [comment]
Unfortunately, this is not Urban Biker issue. Xiaomi changed something with the Mi Fit app or with the Band firmware in the latest update, which broke heart rate data sharing.

Core of the problem is that the Band does not advertise the '_Heart rate_' Bluetooth service anymore. This effectively means it can't be used as a heart rate sensor - the service is not there. You can verify this with any other app, for example the professional nRF Connect app from Nordic Semiconductor, as we did. Even enabling the 'Activity heart rate sharing' option (see the screenshot) did not help. We did our testing with Mi Band 3.

It's just an unhappy coincidence that Urban Biker and Mi Fit/Band were both update these days, but in fact it would be best to address this issue to Xiaomi, or the developer of the Mi Fit app. We can send you any previous Urban Biker apk you need, if you want. Maybe (but just maybe) the v5.14 could work with Mi Band 2, as from v5.15 onward we removed a workaround from our code which forcefully tries to connect Mi Band 2 as a heart rate sensor, even when the service appears as not available.

![image](https://user-images.githubusercontent.com/3844660/61170920-50153c80-a570-11e9-966f-d02c89e5c50d.png)

**Comment by Niflheim123** [comment]
Thank you. It's ok :) this issue can be closed.

**Comment by Sublimis** [comment]
Given the popularity of Mi Band devices and scope of the problem, we rushed to publish an app release with the workaround re-implemented. It's v5.16 release dated 2019-07-13. We're not 100% sure of our earlier claims anymore, but it would be pointless to spend more time researching this now. Please let us know if there should be any more troubles. Thanks for the feedback!
