### ISSUE TITLE
Is there any tricks to open/view one of the SVG files?

### ISSUE THREAD

**Issue by Craig-AMTELCO** [Sublimis/UrbanBiker#39]
Is there any tricks to open/view one of the SVG files? I've tried Chrome and InkScape on Windows 10 and the graph looks almost flat, horizontally. I did not see anything relevant on the FAQ sorry.

**Comment by Sublimis** [comment]
Hi Craig, there's no tricks here, SVG should work without any special treatment when opened with any browser, including Chrome. Please see below for examples:

Firefox:
![image](https://user-images.githubusercontent.com/3844660/62947972-d036f800-bde3-11e9-896f-eb677c5bcdca.png)

Chrome:
![image](https://user-images.githubusercontent.com/3844660/62947988-dc22ba00-bde3-11e9-848f-d8ae4542029b.png)

Opera:
![image](https://user-images.githubusercontent.com/3844660/62948015-e8a71280-bde3-11e9-90e1-69a1d5085a83.png)


As you see, graphs look almost identical among browsers. Could you please send us your SVG file that's causing you troubles so we can take a closer look?

One important thing to consider here is the length of the ride you took. Extremely short rides (like 100-200 meters of distance, 1-2 minutes of duration, or similar) won't have pretty graphs at all, due to digital filtering involved. (The graphs above are taken from a 110 km, 5h 30min ride.)

**Comment by Craig-AMTELCO** [comment]
Thank you for the reply.
Per your request, the SVG I was trying is attached.

The ride is my normal commute, about 15 kilometers, about 45 minutes.


Craig Cullum, Engineering Technologist, AMTELCO
e: craigcu@amtelco.com
f: 608 838 8367
v: 608 838 4194, or 4197, x128

CELEBRATING OUR 40TH YEAR IN 2016!
Please visit us at www.amtelco.com<http://www.amtelco.com/>

**Comment by Sublimis** [comment]
Craig, we haven't received the file, could you please attach it from the web version of the message (not via email)? Thanks!

**Comment by Craig-AMTELCO** [comment]
My apologies for the delay. I did indeed send the file by e-mail earlier.
Meanwhile, the good news is that I can indeed view UB SVG file(s) using Chrome (both Win 10 and OSX (13.6)) after all. I am happier now.
It is interesting that InkScape (0.92.4 on Win10) does not display properly but I am not too interested in troubleshooting that right now.
