### ISSUE TITLE
offline maps not working properly

### ISSUE THREAD

**Issue by varkanoid** [Sublimis/UrbanBiker#4]
I have a problem where I download the great-britain.map from the recommended sources within the app. I place it in the \Galaxy A5 (2017)\Phone\Documents\UrbanBiker\maps location. I then open Urban Biker and it displays the offline map correctly. I then long click on the map button (round globle circle) to switch it to the speed/trip screen. If I then long click the map button to go back to the offline map it shows no map on the background just my position. If I quit out of the app and close all on the phone then go back in it shows no offline map just my GPS position.

I have tried a GB map from three different sources and it does the same thing each time. 

Also have you considered implementing a share option, so you can share the recording tracks with other web pages etc ?

Version 4.13 (2018-05-20) Samsung Galaxy A5 2018

**Comment by hirscholi** [comment]
I can confirm the issue and would like to add that the maps are renamed to *.corrupt after a one time usage.

Galaxy A5(2017)

**Comment by Sublimis** [comment]
Hi, this looks like a serious bug. Unfortunately, we cannot replicate it. Seems like it affects only a handful of devices, like Galaxy A5.

Also, the bug is completely out of our hands at the time being. Our app just sends file location to an offline maps library (Mapsforge), the library does its magic and sends back the data. To the best of our knowledge, this operation should be read-only regarding the offline map file. However, it appears this is not the case and we don't know why.

The best we can do for now is to regularly update Mapsforge library and hope they fixed this. Today we released a new version of the app with updated library (snapshot version), so please try it out. If it still doesn't work, we suggest that you to try filing the bug directly to Mapsforge project at https://github.com/mapsforge/mapsforge/issues.

@varkanoid As for the sharing, yes of course, but haven't had time to implement this yet. Soon! :)

Thanks for the feedback!

**Comment by Sublimis** [comment]
This may be a long shot, but is it possible that the file system is encrypted on your devices? Or in some other way different than 'normal'? We cannot understand why .corrupt files appear in the first place, but it might have something to do with slow access to file system. Also, have you tried restarting the phone? Does the problem appear again, and every time?

**Comment by varkanoid** [comment]
No file system is not encrypted and does it on both phone and SD Card. Yes appears again everytime.

**Comment by Sublimis** [comment]
Please try the newest beta if possible (v4.14.1). We are now marking map files as read-only before allowing the library to access them. Hopefully this will prevent files from being renamed.

**Comment by Sublimis** [comment]
@varkanoid, @hirscholi sorry for tagging you like this, but did you have a chance to try the beta? Does it fix the issue?
