### ISSUE TITLE
Feature Request: Select a specific guide route for overlay

### ISSUE THREAD

**Issue by mduiop** [Sublimis/UrbanBiker#43]
Guide Routes let you store GPX files in folder for overlay but all routes (from multiple files) are all overlayed at once.

Is it possible to choose which route you want displayed as a dotted line . . . i.e. which GPX file is loaded as an overlay onto the map? Would be much more convenient to have a dialog asking which route I want to select as an overlay, rather than having them all jumbled together, or having to remove GPX files from the directory if I don't want them displayed.

To integrate into the interface, one suggestion: The 'display map' screen can have an icon placed somewhere on the screen much like the +/- zoom icons. When you click the icon you can select a file from a listing of the directory contents. The GPX file you choose will be overlayed, and the others ignored for that ride. If you wanted to make it fancier then you can add additional screens for choosing a display name, and editing and all that, but defaulting to the file name as a display name and keeping it at that would be more than sufficient for a v1.0 of this functionality.

All the best, and thanks.

**Comment by Sublimis** [comment]
This can also already be done! :) In the "Select file or folder" dialog for guide routes, simply click on a **file** you want to show, instead of the "Select this folder" button below. The button is there simply to make it possible to select a whole folder. We'll try to make this more intuitive and practical for the future. Thanks for the suggestions and the feedback!
