### ISSUE TITLE
Upload to Google Fit does not work anymore

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#46]
When trying to upload a recorded route to Google Fit an error message shows:
Error uploading, Please check access rights.
(In German: "Fehler bei der Veröffentlichung. Bitte Berechtigungen überprüfen")

Tried to disconnect from Google Fit through the Urban Biker app as well as deleted access for Urban Biker App in Google Fit. Afterwards connected to Google Fit again through the app (which worked fine, Google Fit show access rights for Urban Biker) but still upload attempts end with error message above. 

Any hint what else to try?
Worked flawlessly until recently (unfortunately do not know up to which date/version exactly).

Thanks,
Andreas

**Comment by Sublimis** [comment]
The error message is somewhat misleading, sorry about that. When coded, permissions seemed to be the most probable (if not the only) cause of error that could occur when uploading.

Now, this particular issue seems like a problem on Google part, since we haven't changed anything regarding uploading to Google Fit in our code for the last 8 months or so. There also hasn't been any **official** change in Google Fit that would explain breaking our upload code, as far as we know. So it definitely looks like a Google bug for now.

We are also not the only ones affected: https://stackoverflow.com/questions/57855759/android-google-fit-data-upload-error-5002-datatypes-name-does-not-match-p. We managed to (somewhat) fix the problem using workaround given there, but tracks uploaded this way doesn't show map in Google Fit app (and also no distance, average speed, etc.). So it's not a real solution. It seems like the only option left for us is to wait and see if Google fixes this or gives more information...

**Comment by Scooty66** [comment]
Thanks for the swift reply.
So I will keep on trying and hope for Google to resolve soon.

Andreas

**Comment by Scooty66** [comment]
Hi Sublimis,

sorry to reopen, but currently trying to upload to Google Fit again shows the error:
Error posting, please check permissions again.

Connection to Google Fit in profiles works, just uploading is not possible.
Maybe you aware of a problem at Google again?

Thanks,
Andreas

PS:
I am using UrbanBiker v5.2000

**Comment by Sublimis** [comment]
Hi again! Sorry but we couldn't reproduce the issue (works okay here), and are not aware of any problem at Google. Can you please try again? We haven't changed anything regarding track upload for v5.200 nor v5.201 (moreover, not in the last several months at least), so it shouldn't be something with the app, at least not something we're aware of.

**Comment by Scooty66** [comment]
Last two uploads worked fine, seems to be an issue with just one track from history.
Thanks for your swift reply and tests, no further investigation needed.

Andreas

**Comment by Sublimis** [comment]
Andreas, if you want you can send us the track that won't upload so we can examine the exact problem and see whether this is something that can happen again in the future. Thanks for the feedback!

**Comment by Scooty66** [comment]
Thanks for the support, but I just realised that the track with problems is quite incomplete due to some crashes during recording (see also https://github.com/Sublimis/UrbanBiker/issues/118 ). Goggle might notice this and refuse uploads?
If you still like to have the track, just let me know, no problem sending it.
But I think further analysis is not worth the effort due to bad data quality of this track.
