### ISSUE TITLE
Magene Gemini 210 Speed/Cadence Sensor not working via Bluetooth

### ISSUE THREAD

**Issue by petrwork** [Sublimis/UrbanBiker#47]
It is the same issue as issue #29

https://github.com/Sublimis/UrbanBiker/issues/29

The sensor was working fine, but stop working around Sept 7. I have everything the same as described in #29, every single word there are applicable to my case except phone model. Probably changes that have been made in order to fix #29 have not been included into recent updates. The sensor is recognized and shown as connected on sensors page, but the app doesn't get output from the sensor. Sensor works fine with other app (MyWorkouts). I bought a second sensor and it is doing the exact same.

I have v5.33(2019-09-30) on "Motorola Moto X4 Android one".

**Comment by Sublimis** [comment]
Hi, please set the wheel circumference for the sensor. When the sensor is removed and re-added, wheel circumference is by default "Not set", and we think this is what's going on here.

Please note, speed sensors provide only "clicks" in time, which must be translated to speed by using wheel circumference. Urban Biker won't try to guess the speed if it doesn't know the circumference of the wheel. Instead, it uses GPS-provided speed until it measures wheel circumference, after which it will seamlessly switch to sensor speed. That's why the speed will stay zero when you're stationary but spin the wheel with your hand without setting the circumference first.

You can observe the sensors icon in the status bar; it will stay yellow to indicate that the sensor is connected but the circumference is not (yet) set. It will become green once the circumference is set (or measured).

Workaround for #29 is incorporated in all versions since 05/2019, or v5.10, so this can't be the reason. We can assure you that the Gemini 210 sensor is working fine with the app, as we use it all the time. :)

**Comment by petrwork** [comment]
Yes it resolved the issue. I don't know if it is related but by some reason the second sensor that I use for cadence started to work as well. I reset the cadence censor, but I did it early multiple times with no success. 
Everything is resolved for me. 
Thank you
