### ISSUE TITLE
Cannot set fractional drag area / roll resist coefficients in Power and Energy settings

### ISSUE THREAD

**Issue by PicoPET** [Sublimis/UrbanBiker#5]
**Version:** v4.14 (2018-06-14)
**Platform:** Samsung A5 2017 up-to-date
* Android 8.0.0
* Samsung Experience 9.0
* kernel 3.18.14-13389536-QB17730474)
* account with default locale PL_pl (Polish, decimal fraction separator: comma)

**Symptom:** Cannot enter fractional values for drag area / roll resist coefficients in Power and Energy settings.  Decimal point is ignored, and decimal comma for non-US, non-UK locale is not active (greyed out) on numerical keypad.  Resulting non-fractional values lead to meaningless power and energy data (avg power 5240 W,  total energy 26600 kCal for a bike ride of 20 km with 313m ascent).

**How to reproduce:**
1. Go to Settings->Display->Meters->Power and Energy->Coefficients.
1. Type a fractional value for drag area (Cd·A), e.g., '0.375'.  Only decimal point is available irrespective of language setting (tried Polish and English).
1. Click OK.
1. Value displayed in settings list under "Coefficients" is '375 m²'.
1. Start recording a track and move around.
1. Check the resulting calories and power values which are grossly overshot.

**Note:** The same issue happens with rolling resistance (Crr), but the value is clipped to 1.

**Comment by Sublimis** [comment]
@PicoPET thank you for such detailed report! Apparently this bug has been present in Android at least since 2009. as can be seen here: https://issuetracker.google.com/issues/36907764. Really a shame. Allegedly it has been fixed in Android 8, but not sure if this is true.

In any case, we've introduced a workaround for the v4.15 release that should enable you to enter both a dot and a comma in a number field, regardless of the locale. However, only one will actually work as a decimal point separator; it's up to the user now to figure out which one to use.

We'll release an updated beta version shortly, so you can try it out if you want.

Alternatively, as an immediate workaround simply do like this: Don't erase decimal separator when entering a number, but instead 'recycle' it. Tap on a number field to deselect all digits and position the cursor, and then only erase and modify digits around the decimal separator.
