### ISSUE TITLE
Summary empty

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#50]
Hi there,

do I remember correctly that the Menu/Summary used to show the overall values of all recordings of the active profile?
Because if I access it now no detailed summary data is shown (besides current temperature and air pressure) so I wondered about it.
![Screenshot_2020-01-12-17-55-19-245_com sublimis urbanbiker](https://user-images.githubusercontent.com/5012764/72222474-60c95e00-3565-11ea-9841-e5494b1409ed.jpg)

The overall data still seems to be there, at least some of the summary data is shown if you go to Setting/Profiles and tap on one of the profiles.
![Screenshot_2020-01-12-17-57-14-991_com sublimis urbanbiker](https://user-images.githubusercontent.com/5012764/72222483-67f06c00-3565-11ea-84b9-492a003b9f96.jpg)

As said, I might remember wrong or is there an alternative way of displaying all of the summary data of a profile?

Thanks for a great app and your support,
Andreas

PS: In adddtion, at which location in the file system is the SUMMARY file stored?

**Comment by Scooty66** [comment]
Hi there,

mmh, I seem to be the only one with this problem/wrong memory?
Could someone please then give me a hint in which menu I can find the totals (=summary of all recordings) of a profile?

Thanks for any hint,
Andreas

**Comment by Sublimis** [comment]
Hi, sorry for the late reply! There seems to be some confusion about the Summary screen. It shows live data during recording, not profile totals. We should've probably name it "Live summary" to make its purpose more clear, sorry about that.

Profile totals can be found in the Profiles screen (by going to **Settings>Profiles**, not by long clicking the profile button--this just shows the "Switch profile" screen), just like you said, by expanding a profile entry in the list. Please look at the screenshot below. There's currently no alternative way to display totals for a profile (not there was). The only exception is the "Odometer", i.e. total distance, which can be shown on the main screen just like any other meter/field. For some reason, it's not shown in the (live) Summary screen anymore -- maybe you remember it being shown there in the past.

Summary file for a track is stored inside the track zip file. If you instead meant a profile summary, there's no separate summary file for a profile. Instead, profile summary (i.e. totals) data is stored alongside all other profile configuration, in a JSON file. Every profile has its own JSON config file called `config.json`. These can be found in the `Documents/UrbanBiker/profiles/` folder, by going to a proper subfolder (which is not entirely trivial thing to do, since subfolders are named after profile GUID, not a profile name).

Thanks for the feedback!


![](http://urban-bike-computer.com/screens/v5.31/UrbanBiker_v5.31_17.png)

**Comment by Scooty66** [comment]
Thanks a lot for that very detailed explanation!
