### ISSUE TITLE
Separate and increase the zoom in zoom out buttons

### ISSUE THREAD

**Issue by radiotbo** [Sublimis/UrbanBiker#61]
Is it possible to increase the size as well separate the zoom in / zoom out button in the map screen? In mtb and in movement it is difficult to control where you put your finger on. Thank you.

**Comment by Sublimis** [comment]
Hi! Two small zoom buttons you see on the map are the default buttons provided by the Google map, and unfortunately cannot be customized. The only possibility would be for us to create our own, but we (kind of) already did this -- please read below.

For your use case, there are two recommended ways to zoom the map:

1. Use the map zoom **gestures**. Those include pinching, tapping, etc. Please see the complete list here: https://developers.google.com/maps/documentation/android-sdk/controls#zoom_gestures. This is great because almost the whole screen can be used to make a gesture and zoom the map.

2. Use the Quick Zoom buttons provided by our app. These are the two other two bigger "Quick Zoom" covert buttons at the bottom of the map. Button areas are shortly visible when map is shown, and then hidden while remaining active. When tapped, you can zoom in/out 3x more quickly than with the default buttons.

**Comment by radiotbo** [comment]
Thank you. Thats perfect, I thought that the default buttons were the quick zoom ones. Thats perfect, in movement and with gloves gesture for zoom in/out are very imprecise and dangerous.
