### ISSUE TITLE
kcal calculation from sensor data only?

### ISSUE THREAD

**Issue by natewill11** [Sublimis/UrbanBiker#63]
I don;t use GPS because I keep my phone in my pocket when riding.  When I use the app (connected to my duotrap s) speed and distance and everything is great! but energy (kcal) remains at zero.  Is it possible to have the app calculate energy from sensor data alone, without relying on GPS data?

**Comment by Sublimis** [comment]
Hi, yes, and the issue has been implemented/fixed just now. The upcoming version v5.70 will behave the way you described.

However, please note that it's perfectly okay to have GPS enabled even when you carry your phone in a pocket. The GPS signal in a pocket is usually not much worse than outside of the pocket.

Also note that if your phone does not have a barometer sensor, the power and energy calculations won't be so accurate -- There's no altitude information in this case (without GPS), so ascents and descents cannot be detected.

**Comment by natewill11** [comment]
Hello,

I have been using your app for a few months now, and I love it!  I upgraded
to the paid version for what it's worth.

A quick question: can I get a bit more information on how your app
calculates calories burned?  Specifically, I'm wondering if the
calculations will be more accurate if I add a cadence sensor, a heart rate
monitor, or other sensors to the equation.  Currently I only use GPS and a
speed sensor.

Regards,

Nathan Willis

**Comment by Sublimis** [comment]
Hi Nathan, sorry for the delay. Two essential ingredients when calculating cycling power (and thus energy spent) are:

1. **Speed**. You already have this covered with your speed sensor.
2. **Altitude change**. If your phone doesn't have barometer sensor, then you should really get yourself one that has. GPS simply cannot provide precise altitude changes.

Cadence and heart rate sensors are not used when calculating energy spent (calories). Heart rate is important mostly just for stationary workouts, where calories cannot be calculated via kinematics. [It would be just a minor correction otherwise, and this can be taken into account simply by adjusting the "Overall thermal efficiency" parameter by a percent or two.] Similar story for cadence. Earlier we had an idea to also use cadence to somewhat adjust energy calculations, but then realized it's not plausible.

If you're really into getting the most accurate power and energy values, you should get yourself a dedicated power sensor. They are not cheap, though. If this is too much money to spent, simply getting a phone with a barometer and using a speed sensor will get you excellent results.

Hope this helps. Thanks for the feedback!

**Comment by natewill11** [comment]
Cool!  Thanks for the feedback.
