### ISSUE TITLE
Folder for offline map Simple Dash, unable to change

### ISSUE THREAD

**Issue by XtSpot** [Sublimis/UrbanBiker#65]
I would change de folder for offline map, but I went a step to deep.
Now it show only a Dash "/" and I can't select it.
I already made 
- Reset of cache and data.
- Reinstall the application.

Strangly the reset and reinstallation, do not do a reset of this parameter.
But from now it always show a simple Dash. and I can't change it.
Is there another to way to make a reset of this parameter ?

**Comment by Sublimis** [comment]
Yes, of course! Please simply click the "**Reset to default**" button below, in Setting screen. This will reset the folder to a default path, and you can then once again browse for your wanted folder/file.

This parameter is not reset after reinstall because almost all app config is saved to the `/Documents/UrbanBiker/` folder on _external_ storage, and this is not removed on uninstall. Your finished tracks are also saved there (but not unfinished ones - they are lost on uninstall!), so be cautious if deleting anything.

Thanks for the feedback!
