### ISSUE TITLE
GPS, Speedometer Problem

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#68]
I am using the newest Beta (5.80) and while driving the speed somehow is shown to be extremly slow at some point although the map indicates GPS is working correctly. Pause and Unpause the app gives the correct speed immediately till the next incidence. I had this problem already in the previously beta.

**Comment by Sublimis** [comment]
Hi, are you using a speed sensor, or just the GPS? It's strange if you're just using GPS, as we haven't changed anything regarding this in a while. With the information provided it seems more likely that this is a classical GPS signal interference. You can try toggling the Settings > Tracking > Advanced > Recalculate speed option, maybe this helps a bit.

You also can't usually tell from the map that the GPS signal used for speed is accurate. It's better to look at the color of the GPS icon in the status bar, however this is also not 100 % reliable. This icon usually provides the "visible satellites" status, which also might not be related to a speed accuracy at all.

Thanks for the feedback!

**Comment by JHenneberg** [comment]
hello, 
Hello
Hello
Hello, no pure GPS I am using. I went for a ride today again. I recorded now using komoot and urban biker. I payed pretty much attention to the app (urban biker). A few times the overlay could not keep up for a while maybe 30sec (speed was still shown and also the symbol for the current location, color was blue not red). The drop of speed happened again. Uploading to strava the kommot file is fine the urban biker one is not. I could provide both gpx files if this is helpful.  

I also did not change anything with my phone. No new OS either. Pretty bad because I like the App very much.

**Comment by Sublimis** [comment]
It would be extremely helpful if you could provide those GPX files, thanks. You can drop us an email with the files attached.

Couple of questions:

1. What do you mean by "the overlay could not keep up for a while", and what exactly is "the overlay"?
2. Which option do you have set in _Settings > Tracking/GPS > Advanced > GPS provider_?

Sorry, the things from the changelog you mention do not have influence on this. In fact, we've checked our internal (more detailed) changelog for the last couple of versions, and see nothing connected to your issue. Either we're mistaken about the changelog, or the issue is a rather old one, but comes to surface only in some special (yet unknown) circumstances. Your GPX files will probably shed some light on this.

**Comment by JHenneberg** [comment]
I was thinking yesterday if I really did not change anything again after your comment. I went through battery settings, permissions (only gps when app is in foreground) etc. I also checked the settings of urban bike itself like you mentioned. Accidentally the Bluetooth screen appears and I saw that all sensors were connected about an hour ago. Also a wahoo speed sensor I used before and immediately I knew what I did change. I changed my bag for spare tyre to an old one and in there was laying the speed sensor 🙈 not giving any useful data. Thanks again for the great support and the inconvenience.
