### ISSUE TITLE
Strava sync powermeter symbol, although not using any power meter

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#81]
Hello,

in one of the recent updates the sync with strava concerning the power changed. On strava I can see now the symbol (lighning bolt) behind my power output, although I am not using an powermeter and the power is calculated in a different way. Is there a reason why you changed this and is there maybe a possibility to turn this off? I would like to have this symbol only when I am actually using a power meter.

Greetings Julian

**Comment by Sublimis** [comment]
Hi Julian, before v5.91 Strava would ignore power values given by Urban Biker. It would estimate power instead, and show "Estimated power" instead of "Power". Estimated power has no real chance of being more accurate than the power calculated by UB in real time even without a power meter, esp. if barometer and speed sensor are used and everything is properly set up (weights and coefficients).

We could provide an option to turn this feature off, and let Strava estimate power instead. But is this really what you want? Strava might easily remove the bolt symbol in the future, and you'll end up with just the estimated powers. Maybe it would be better to use some other means of marking activities where you used power meter, for example in activity description?

**Comment by JHenneberg** [comment]
Hey,

for me the power is not relevant as long as it is not coming from an power meter, because as you also commented in a different issue the calculation is based on a lot of assumptions. The weight of rotating and rotating masses etc can be measured exactly, but factors like wind, air resistance dynamic (change in body position) is neglected and those are the significant values when you reach a certain speed. 

Strava is calculating an estimated power and so is Urban Biker. They are both doing this nearly on the same assumptions when I put my body weight and bicycle weight on strava. How Urban Biker is more accurate (beside you can configure more parameters) when it is relying on the same data?

Anyway for me it is important that I can turn it off so that I know for sure when I was using an power meter and when my power was estimated (by strava or urban biker).

According to https://support.strava.com/hc/en-us/articles/216919427-How-to-Get-Power-for-Your-Rides the "lightning bolt" is indicating a power meter was used, so actually Urban Biker is circumventing this.

**Comment by Sublimis** [comment]
Julian, whenever Strava detects a `<power>` tag inside the uploaded GPX, they will put the lightning bolt icon. It's as simple as that. But in fact, it's too simple.

They are making a mistake assuming that the data inside a `<power>` tag must have come from a dedicated power meter, and are not estimated (not to say "measured") by other means. Nothing in the standard tells this must be so. It's like assuming all location points came from GPS satellites, and indicating this with a GPS logo icon, while in reality the locations could have come from GLONASS, BeiDou, Galileo, a combination, or an estimation.

There's a lot of reasons how Urban Biker is more accurate in estimating power:

- In UB you can adjust all parameters governing power calculations, like drag area, rolling resistance, total weight, rotating weight, even air temperature can be taken into account. In Strava, you can only adjust total weight.

- Urban Biker uses superior barometric altitudes on devices with a barometer, while Strava can only peg on this data, or use a database of elevations in post-processing (which has no theoretical chance of being more accurate than barometric altitudes).

- Urban Biker can use speed sensors for superior accuracy of speed, while Strava cannot.

- A few more reasons that would go beyond the purpose of this text.

Just observe and compare power graphs obtained from Urban Biker with that from Strava in estimation mode, to see how much more inaccurate they are. Here's an example:

Urban Biker:
![ub_estimated_power](https://user-images.githubusercontent.com/3844660/86242895-ade9cc80-bba5-11ea-8608-91373559cc8f.png)

Strava:
![strava_estimated_power](https://user-images.githubusercontent.com/3844660/86242880-a9251880-bba5-11ea-8b23-317f2da49ffd.png)

This is the same example ride, both apps were used side-by-side on the same device. You can see how the max power on Strava goes up to about 1300 watts, and looks nothing like the graph from UB. The bike was equipped with a speed sensor, and Strava cannot use these sensors. Thus you can also observe how speed graph from Strava is very inaccurate. But speed is also essential for accurate power calculations. (The "hole" around the 12 km mark is from the UB's FenceGuard effects, which Strava cannot handle well. The hole is not present in graphs that UB creates.)

Air resistance is not neglected in power calculations. Together with altitude changes, it's top contributing factor to power, so it must be taken into account. Drag area parameter governs this in our app. In Strava, this value is an obscured constant. Change in body position is not so important for air drag, as standing position is mainly used while going uphill, where gravity is prevalent power factor, not air drag.

Wind factor is much more important of course, but when doing a circular ride its contributions tend to cancel out on average :) We do plan to implement a wind option one day, for estimating wind effects.

Back to the original request, yes, we understand your use case, and will provide an option to turn off sending power to Strava. Not that it is a right thing to do. It would be best if they allowed some other means of indicating that power meter is being used, like they are doing e.g. for barometer. If barometer is being used for altitudes, they allow an app to indicate this in the GPX file, instead of just unashamedly assuming that altitudes did, or did not, came from a device with a barometer. You can read more about this and the `<power>` tags here: https://developers.strava.com/docs/uploads/.

Thanks for the feedback!

**Comment by Sublimis** [comment]
Hi, there's an option called **Power data upload policy** in **Settings > Accounts** screen starting from the v5.101 beta, which can be used to prevent power data upload unless a power meter was used for an activity. The default is to always upload power data, so be sure to set this up according to your preferences. The setting is valid for all profiles.

Also note that activities recorded with app versions before v5.101 beta do not have the "power meter was used" flag inscribed into them. This means that older activities are always considered as **not** recorded using a power meter. This is worth having in mind if you want to upload an older activity together with original power data. In that case, you should first set the **Power data upload policy** setting back to the default "Always", and then upload your old activity. ⚡
