### ISSUE TITLE
Favero Assioma power/cadence sensor stops working after a few sessions

### ISSUE THREAD

**Issue by zett42** [Sublimis/UrbanBiker#98]
Favero Assioma is a powermeter that also reports cadence. Power is always reported fine. Cadence works for a few sessions after adding the sensor to the profile. After a random number of rides, cadence stops working (value stays at zero from the beginning of the recording).
A workaround is to remove the sensor from the profile and add it back again.

Sensor settings:
[x] use for power
[ ] use for speed
[x] use for cadence 
[ ] use for distance and duration

Firmware version: 04.25

Sensor is connected via BLE.

**Comment by zett42** [comment]
I have to correct. Today it didn't record power, but only cadence! Very strange. 
Let me know how I can help to debug.

**Comment by Sublimis** [comment]
We've checked everything and can't find an issue with the code.* The code which manages power/speed/cadence sensors wasn't touched for a few months now, so whatever problem is surfacing now it should've been there and observable during the last few months.

We've noticed that ANT+ has updated their services/plugins lately, maybe this could be a culprit. Can you please double-check you're not using the sensor in ANT+ mode? Basically the only way to be sure is to observe the icon beside the sensor name in the Sensors screen.

Additionally, can you please check whether cadence/power data is saved normally to SVG graph files during that time when it's not updating on the screen? If you can, maybe it would be best to send us a complete track ZIP file of a track where cadence or power data failed so we can analyze.

*In fact, we did find one bug which appears to be benign, and probably unobservable under normal operation. This was fixed in the latest [beta version](https://play.google.com/apps/testing/com.sublimis.urbanbiker) today, if you can it would also be best if you try with it.

Thanks for the feedback!

**Comment by zett42** [comment]
Thanks for your response! 

> I have to correct. Today it didn't record power, but only cadence! Very strange.

To be precise, yesterday it was showing power and cadence during the whole ride, it just didn't record power (actually the GPX file has a few gpxpx:PowerInWatts elements with value of 0). 

> We've noticed that ANT+ has updated their services/plugins lately, maybe this could be a culprit. Can you please double-check you're not using the sensor in ANT+ mode? 

The phone (LG G7) doesn't support ANT+ on the hardware side, so this can be ruled out.

I will have a deeper look at the other track files, where it didn't show cadence during the ride. I will send the data by mail later this day. I've also switched to BETA.

**Comment by zett42** [comment]
Last three rides with BETA (5.107) all showed both power and cadence with reasonable values. I didn't have to remove/add the sensor again. The GPX files had gpxpx:PowerInWatts elements for each track point, except for very few at the beginning and the end, which is to be expected.

I will keep an eye on this and if the issue happens again with BETA, I will send you track files.

**Comment by zett42** [comment]
Did an almost 11h ride today and no issues. 👍

**Comment by JHenneberg** [comment]
@zett42 impressive. You had an external battery pack or which phone you have?

**Comment by zett42** [comment]
@JHenneberg 
The phone has a 3000 mAh battery which after 3 years is now rather weak, but still good enough for up to 4 h ride.
I'm using a 6800 mAh external battery pack which was enough to load the phone from 13% to 100% again and even keep it there until the end of the ride!

I have to add that I configured the navigation app to turn the display on only when needed for turn instructions. Sometimes I  kept it on a little bit longer when crossing urban areas.

**Comment by december-soul** [comment]
I  have the Power2Max (P2M) Powermeter which also includes the cadence.
On Zwift this will work perfect. (Power and Cadence)

On UrbanBiker the Cadence Sensor will not work, shows always 0.
It also shows 0 during the ride.

I use the current beta.
Can i give you some more information?

**Comment by zett42** [comment]
I'm closing this as the problem has been fixed for me with v5.107.
@december-soul I think it would be better to open a separate issue for Power2Max, as this could be hardware-specific.

**Comment by Sublimis** [comment]
> I have the Power2Max (P2M) Powermeter which also includes the cadence.
> On Zwift it works perfect. (Power and Cadence)
> 
> On UrbanBiker the Cadence Sensor will not work, shows always 0.
> It also shows 0 during the ride.

Sorry, no idea at this time what could be wrong here. One thing you can try, is to enable "Data filtering" feature in the sensor properties screen, and see if it helps. Please let us know, and thanks for the feedback!
